version: '3.1'

networks:
  webnet:
    driver: bridge

services:
  kkris-codes:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: "production"
    restart: unless-stopped
    networks:
      - webnet
    ports:
      - "3000:3000"
    environment:
      HOST: "0.0.0.0"
